### ISSUE TITLE
Almost doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [Misfit-Developers/LinkSDKExamples#1]
I run the app it tries to connect to misfit link, jumps to original misfit app and finally writes that "I need download my app from app store" (the app from this example) and nothing works

**Comment by misfitphill** [comment]
is the Misfit Link app installed on your device?

**Comment by gerchicov-bp** [comment]
yes, synchronized with hardware Link and hardware Link's firmware is updated

**Comment by misfitphill** [comment]
ok, this issue should be fixed. Please make sure the appId and secret are:
AppId:@"43880" appSecret:@"PKbRDAg4yptCySRqptaCunOEpYHjI26V"

you can make this change in the connectToMisfit method in LTMainViewController.m or re-download the LinkSDKExamples project. Please let us know if this does not fix the issue.

**Comment by gerchicov-bp** [comment]
yes, it fixes the issue.

https://build.misfit.com/docs/link/link_sdk

maybe is something wrong with "test users" list? I didn't perform steps 8-10 because I just started an app and it is not ready yet.

**Comment by misfitphill** [comment]
Good to hear this issue is fixed. For testing the Lap Timer app, you should not need to perform any of the steps listed in the link sdk documentation. The link sdk app for the Lap Timer app has already been setup.

**Comment by gerchicov-bp** [comment]
Thanks, it will be enough for testing in the very near future. I hope you will fix it for other app ids
